name: amap_view_muka_example
publish_to: none
description: Demonstrates how to use the amap_view_muka plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies: 
  flutter_easyrefresh: ^2.2.1
  cupertino_icons: ^1.0.2
  widget2image: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  permission_handler: ^10.2.0
  bitmap: ^0.1.3
  amap_view_muka: 
    path: ../
  amap_search_muka: 
    path: ../../amap_search_muka

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/map.png
    - assets/style.data
    - assets/style_extra.data
  uses-material-design: true

